---

- name: Generate libvirt Terraform files
  include: libvirt-provider.yml
  loop: '{{ vms }}'
  when: item.provider == 'libvirt'

# - name: Generate proxmox Terraform files
#   include: proxmox-provider.yml
#   loop: '{{ vm }}'
#   when: item.provider == 'proxmox'